apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: stock-con-ingress
  labels:
    app: stock-con
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host:
    http:
      paths:
      - path: /stock-con
        backend:
          serviceName: stock-con
          servicePort: 80